### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'Figures/res1_tuto1.png'

### ISSUE THREAD

**Issue by huchuanyue** [SedFoam/sedfoam#1]
Dear contributors,
I met a problem when I using the command 'python plot_tutoSedimentation.py' in the folder 'sedfoam/tutorials/Py', after running the case '1DSedim'.
I got the following error：

Traceback (most recent call last):
  File "plot_tutoSedimentation.py", line 131, in <module>
    edgecolor='w', format='png')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 222, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 2252, in print_figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 550, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 2] No such file or directory: 'Figures/res1_tuto1.png'

The version of my matplotlib is 2.0.2. Do I install a wrong version of matplotlib? 
Thanks a lot！

**Comment by CyrilleBonamy** [comment]
Hello,

I think there is a missing information in the tutorial documentation :
The directory 'Figures' must be created before the use of python scripts.

So if you use the command 'mkdir Figures' in the folder 'sedfoam/tutorials/Py', everything will be fine.

Tell me if I have it right.

Cyrille

----- Mail original -----
De: "huchuanyue" <notifications@github.com>
À: "SedFoam/sedfoam" <sedfoam@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Envoyé: Samedi 26 Août 2017 13:57:38
Objet: [SedFoam/sedfoam] IOError: [Errno 2] No such file or directory: 'Figures/res1_tuto1.png' (#1)

Dear contributors,
I met a problem when I using the command 'python plot_tutoSedimentation.py' in the folder 'sedfoam/tutorials/Py', after running the case '1DSedim'.
I got the following error：

Traceback (most recent call last):
  File "plot_tutoSedimentation.py", line 131, in <module>
    edgecolor='w', format='png')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 222, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 2252, in print_figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 550, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 2] No such file or directory: 'Figures/res1_tuto1.png'

The version of my matplotlib is 2.0.2. Do I install a wrong version of matplotlib? 
Thanks a lot！

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/SedFoam/sedfoam/issues/1

**Comment by huchuanyue** [comment]
You are right!
I do as you said, and everything goes well.
Thank you!
